services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  # backend:
  #   command: uvicorn src:app --host 0.0.0.0 --port 8000 --reload
  #   volumes:
  #     - .:/src
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - redis

  # worker:
  #   build: .
  #   command: celery -A src.worker.celery worker --loglevel=info
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - redis
